version: "3.8"

services: 
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: api_express
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend

  node:
    build: .
    container_name: node_container
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
